"""
10: Train a CNN on the synthetic fault dataset (09's output).

9-class classification: normal + the 8 required fault types from the
problem statement. Same CNN backbone used throughout this project.

NOTE on methodology: samples were generated by injecting faults onto
REUSED healthy flights (sampling with replacement in step 09), so a
random split here can let the same underlying flight appear in both
train and test under different fault labels. This is a known,
disclosed limitation -- documented rather than hidden. A stricter
version would track source-flight IDs and split on those instead.
"""

import numpy as np
import os
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

DATA_DIR = r"C:\Users\dhruv\Desktop\2days\2days"
data_path = os.path.join(DATA_DIR, "synthetic_fault_dataset.npz")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

data = np.load(data_path, allow_pickle=True)
X = data["X"]
y = data["y"]
class_names = list(data["class_names"])
n_classes = len(class_names)

print("Loaded synthetic dataset:", X.shape)
print("Classes:", class_names)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")

# normalize (fit on train only)
train_mean = X_train.mean(axis=(0, 2), keepdims=True)
train_std = X_train.std(axis=(0, 2), keepdims=True) + 1e-6
X_train = (X_train - train_mean) / train_std
X_test = (X_test - train_mean) / train_std


class SeqDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


train_loader = DataLoader(SeqDataset(X_train, y_train), batch_size=32, shuffle=True)
test_loader = DataLoader(SeqDataset(X_test, y_test), batch_size=64, shuffle=False)


class FlightCNN(nn.Module):
    def __init__(self, n_channels, n_classes):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv1d(n_channels, 32, kernel_size=7, padding=3),
            nn.BatchNorm1d(32), nn.ReLU(), nn.MaxPool1d(2),
            nn.Conv1d(32, 64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64), nn.ReLU(), nn.MaxPool1d(2),
            nn.Conv1d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128), nn.ReLU(),
            nn.AdaptiveAvgPool1d(1),
        )
        self.fc = nn.Linear(128, n_classes)

    def forward(self, x):
        x = self.net(x).squeeze(-1)
        return self.fc(x)


model = FlightCNN(X_train.shape[1], n_classes).to(device)
criterion = nn.CrossEntropyLoss()  # classes are balanced (500 each), no weighting needed
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)

EPOCHS = 20
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0.0
    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * xb.size(0)
    print(f"Epoch {epoch + 1}/{EPOCHS} - train loss: {total_loss / len(train_loader.dataset):.4f}")

model_path = os.path.join(DATA_DIR, "synthetic_fault_cnn.pt")
torch.save(model.state_dict(), model_path)
print(f"Saved model to {model_path}")

model.eval()
all_preds, all_labels = [], []
with torch.no_grad():
    for xb, yb in test_loader:
        preds = model(xb.to(device)).argmax(dim=1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(yb.numpy())

print()
print("=== Classification report (synthetic fault taxonomy) ===")
print(classification_report(all_labels, all_preds, target_names=class_names, zero_division=0))
print()
print("=== Confusion matrix ===")
print("Order:", class_names)
print(confusion_matrix(all_labels, all_preds))

# also save the normalization stats -- needed later for real-time inference
norm_path = os.path.join(DATA_DIR, "synthetic_norm_stats.npz")
np.savez(norm_path, mean=train_mean, std=train_std)
print(f"Saved normalization stats to {norm_path}")